Fix GRUB booting on amd64 Ubuntu targets
GRUB bootloader requires linuxefi module to be installed on Ubuntu
targets under amd64 architecture.

Otherwise following error will occur:

error: file `/EFI/BOOT/x86_64-efi/linuxefi.mod' not found.

Signed-off-by: Anton Mikanovich <amikan@ilbers.de>