initramfs: Fix detection of kernel image
This can also be vmlinuz-.... Broken like this when using the class for
x86 e.g.:

Log data follows:
| DEBUG: Executing python function sstate_task_prefunc
| DEBUG: Python function sstate_task_prefunc finished
| DEBUG: Executing shell function do_generate_initramfs
| update-initramfs: Generating /boot/initrd.img-vmlinux*
| W: No zstd in /usr/bin:/sbin:/bin, using gzip
| grep: /boot/config-vmlinux*: No such file or directory
| E: gzip compression (CONFIG_RD_GZIP) not supported by kernel
| update-initramfs: failed for /boot/initrd.img-vmlinux* with 1.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/build/../work/recipes-initramfs/cip-core-initramfs/cip-core-initramfs.bb:do_generate_initramfs) failed with exit code '1'

Reported-by: Venkata Pyla <venkata.pyla@toshiba-tsip.com>
Fixes: 961a56828ca3 ("classes/initramfs: Print messages in case of a build error")
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>