CI: Fix paths for the latest Avocado version
We can't use relative path for logdir in Avocado 89.0+ because it fails with:

FileNotFoundError: [Errno 2] No such file or directory: '.../whiteboard'

Move to absolute paths to be able to use the latest version.

Signed-off-by: Anton Mikanovich <amikan@ilbers.de>