sdk: Avoid parsing errors when DISTRO_ARCH is not yet set
In multiconfig setups, it can happen during some parsing steps that a
machine and, thus, a concrete DISTRO_ARCH is not yet set, leading to

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 4, function: <module>
     0001:__anon_158__build____work_isar_meta_classes_base_bbclass(d)
     0002:__anon_162__build____work_isar_meta_classes_sstate_bbclass(d)
     0003:__anon_56__build____work_isar_meta_classes_image_bbclass(d)
 *** 0004:__anon_56__build____work_isar_meta_classes_sdk_bbclass(d)
     0005:__anon_21__build____work_isar_meta_classes_buildchroot_bbclass(d)
     0006:__anon_84__build____work_isar_meta_classes_imagetypes_wic_bbclass(d)
     0007:__anon_24__build____work_isar_meta_classes_imagetypes_container_bbclass(d)
     0008:__anon_305__build____work_isar_meta_classes_image_bbclass(d)
File: '/build/../work/isar/meta/classes/sdk.bbclass', lineno: 52, function: __anon_56__build____work_isar_meta_classes_sdk_bbclass
     0048:    distro_arch = d.getVar('DISTRO_ARCH')
     0049:    if mode == "0" or d.getVar('HOST_ARCH') ==  distro_arch:
     0050:        toolchain = "build-essential"
     0051:    else:
 *** 0052:        toolchain = "crossbuild-essential-" + distro_arch
     0053:    if d.getVar('ISAR_ENABLE_COMPAT_ARCH', True) == "1":
     0054:        toolchain += " crossbuild-essential-" + d.getVar('COMPAT_DISTRO_ARCH')
     0055:    d.setVar('TOOLCHAIN', toolchain)
     0056:}
Exception: TypeError: can only concatenate str (not "NoneType") to str

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>