wic/plugins: fix kernel version detection for bios
When building an image with legacy bios using wic, wic can fail to pick
up the initrd.

ERROR: _exec_cmd: install -m 0644 /build/tmp/work/debian-buster-amd64/bla-image-qemux86-64-wic-img/0.2-r0/rootfs/boot/initrd.img-4.19.0-1-amd64 /tmp/tmp.7x9N9Wo4wZ/bla-image-debian-buster-qemux86-64.wic/tmp.wic.r10macew/hdd/boot/initrd.img-4.19.0-1-amd64 returned '1' instead of 0
output: install: cannot stat '/build/tmp/work/debian-buster-amd64/bla-image-qemux86-64-wic-img/0.2-r0/rootfs/boot/initrd.img-4.19.0-1-amd64': No such file or directory

The mechanism used to "cut off the end" seems to cut off too much.

>>> "vmlinuz-4.19.0-14-amd64".strip('-' + 'amd64')
'vmlinuz-4.19.0-1'

But indeed we would hope for 'vmlinuz-4.19.0-14'. The issue affects all
versions ending with 4 and 6, because '-amd64' is used as a set of
characters to be stripped anywhere in the string. Using strip() is
completely wrong here.

Signed-off-by: Henning Schild <henning.schild@siemens.com>