testsuite: Add KFAIL to qemuarm64-resolute
Currently, the following error occurs when building qemuarm64-resolute:
ERROR: mc:qemuarm64-resolute:example-module-generic-1.0-r0 do_dpkg_build: ExecutionError('/build/tmp/work/ubuntu-resolute-arm64/example-module-generic/1.0-r0/temp/run.dpkg_runbuild.155703', 3, None, None)
The task log shows:
tar: src/Makefile: Cannot open: Function not implemented
tar: src/debian: Cannot mkdir: Function not implemented
tar: src/debian/changelog: Cannot open: Function not implemented
tar: src/debian/control: Cannot open: Function not implemented
tar: src/debian/control.tmpl: Cannot open: Function not implemented
tar: src/debian/postinst: Cannot open: Function not implemented
tar: src/debian/rules: Cannot open: Function not implemented
tar: src/debian/rules.tmpl: Cannot open: Function not implemented
tar: src/example-module.c: Cannot open: Function not implemented
tar: Exiting with failure status due to previous errors
dpkg-source: error: tar -xf - --no-same-permissions --no-same-owner subprocess failed with exit status 2
E: FAILED [dpkg-source died]

This issue started to occur after Ubuntu updated tar to
tar_1.35+dfsg-4ubuntu0.2 and is also present in tar_1.35+dfsg-4ubuntu0.3
and tar_1.35+dfsg-4ubuntu0.4.

Mark this target as KFAIL until the Ubuntu tar issue is fixed.

Signed-off-by: Zhihang Wei <wzh@ilbers.de>