linux-custom: linux-header: copy selinux headers
Copy the selinux headers, as it is required to build scripts on target

root@iot2050:/usr/src/linux-headers-4.19.165-cip41-rt18+mel6# make scripts
...
HOSTCC  scripts/selinux/genheaders/genheaders
scripts/selinux/genheaders/genheaders.c:18:10: fatal error: classmap.h: No such file or directory
 #include "classmap.h"
          ^~~~~~~~~~~~
compilation terminated.

Signed-off-by: Arulpandiyan Vadivel <arulpandiyan_vadivel@mentor.com>