isar-sstate: fix failures if a variable is set to just whitespace
We see this failure if a variable is set to the empty string, as whitespace is
being stripped off of the variable after we check if the value is empty or None,
not before.

    Traceback (most recent call last):
    File "/home/kergoth/Code/indos/signatures/isar/scripts/isar-sstate", line 941, in <module>
        sys.exit(main())
                ^^^^^^
    File "/home/kergoth/Code/indos/signatures/isar/scripts/isar-sstate", line 937, in main
        return globals()[f'sstate_{args.command}'](**vars(args))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/kergoth/Code/indos/signatures/isar/scripts/isar-sstate", line 894, in sstate_lint
        if not val[0] == '/':
            ~~~^^^
    IndexError: string index out of range

Signed-off-by: Christopher Larson <chris.larson@siemens.com>