isoimage-isohybrid-isar: fix error if source_param image_name is set
This fixes the following error:

 ERROR: _exec_cmd: export PATH=//sbin://usr/sbin://usr/bin://usr/bin/None://bin:None:$PATH;/usr/bin/python3-native/python3 /usr/bin/bmaptool create /tmp/isar-image-base-debian-bookworm-qemuamd64-iso.wic/tmp.wic.h061sjt6/isohybrid-efi-202511201339-cd.direct -o /tmp/isar-image-base-debian-bookworm-qemuamd64-iso.wic/tmp.wic.h061sjt6/isohybrid-efi-202511201339-cd.direct.bmap returned '1' instead of 0
| output: bmaptool: ERROR: An error occurred, here is the traceback:
| Traceback (most recent call last):
|   File "/usr/lib/python3/dist-packages/bmaptools/BmapCreate.py", line 200, in _open_image_file
|     self._f_image = open(self._image_path, 'rb')
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| FileNotFoundError: [Errno 2] No such file or directory: '/tmp/isar-image-base-debian-bookworm-qemuamd64-iso.wic/tmp.wic.h061sjt6/isohybrid-efi-202511201339-cd.direct'
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
|   File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 555, in create_command
|     creator = BmapCreate.BmapCreate(args.image, output, "sha256")
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib/python3/dist-packages/bmaptools/BmapCreate.py", line 166, in __init__
|     self._open_image_file()
|   File "/usr/lib/python3/dist-packages/bmaptools/BmapCreate.py", line 202, in _open_image_file
|     raise Error("cannot open image file '%s': %s"
|
| bmaptool: ERROR: cannot open image file '/tmp/isar-image-base-debian-bookworm-qemuamd64-iso.wic/tmp.wic.h061sjt6/isohybrid-efi-202511201339-cd.direct': [Errno 2] No such file or directory: '/tmp/isar-image-base-debian-bookworm-qemuamd64-iso.wic/tmp.wic.h061sjt6/isohybrid-efi-202511201339-cd.direct'

Tested-by:     Herbert Bernecker <herbert.bernecker@siemens.com>
Signed-off-by: Quirin Gylstorff <quirin.gylstorff@siemens.com>