customizations: defer IMAGE variable expansion in CUSTOMIZATION_VARS
The previous logic for conditionally adding the IMAGE variable to
CUSTOMIZATION_VARS suffered from a Bitbake variable expansion
timing issue.

The original line `CUSTOMIZATION_VARS_IMAGE ?= "${IMAGE}"` would evaluate
the `${IMAGE}` variable too early in the parsing process. If `IMAGE` had
not yet been fully defined or resolved to its final value (e.g.,
`isar-image-base`), `CUSTOMIZATION_VARS_IMAGE` would incorrectly store
the literal string `"${IMAGE}"`.

Consequently, when `CUSTOMIZATION_VARS` was later appended using a
Python expression that retrieved `CUSTOMIZATION_VARS_IMAGE`, it would
receive this unexpanded literal string. This led to build failures and
errors such as:

  ERROR: ... Unable to get checksum for ... ${IMAGE} SRC_URI entry ...

Introduce a new Bitbake override, `:customization-for-images`, which
is conditionally activated when `CUSTOMIZATION_FOR_IMAGES` is set (to
preserve the initial semantic of 9a2919be). The `IMAGE` variable is
then appended to `CUSTOMIZATION_VARS` specifically within this override
context:

  `CUSTOMIZATION_VARS:append:customization-for-images = " ${IMAGE}"`

By associating the append operation with an override, the expansion is
deferred and ensures that `${IMAGE}` is properly resolved to its value
before being added to `CUSTOMIZATION_VARS`.

Fixes: 9a2919be
Signed-off-by: Cedric Hombourger <cedric.hombourger@siemens.com>