fix: move squashfs class from meta-isar to isar
The squashfs class was provided by the meta-isar layer, but referenced
in the meta layer. By that, downstream users that only imported the meta
layer run into a parsing error:
 ERROR: ParseError at /work/build/../isar/meta/classes/image.bbclass:134:
        Could not inherit file classes/squashfs.bbclass

We fix this by moving the class to the meta layer.

Fixes: 822444f3 ("move squashfs imagetype class from CIP to ISAR")
Signed-off-by: Felix Moessbauer <felix.moessbauer@siemens.com>